import { render } from '@testing-library/react';
import { createElement } from 'react';
import { describe, expect, it } from 'vitest';

import * as iconsModule from '../src/index';
import { createIcon, type IconProps } from '../src/create-icon';

type IconComponent = (props: IconProps) => React.ReactElement;

const entries = Object.entries(iconsModule).filter(
  ([name, value]) => name.endsWith('Icon') && typeof value === 'function' && name !== 'createIcon',
) as [string, IconComponent][];

/**
 * The set is generated by merging two hand-drawn sources, so the risks worth
 * asserting are structural: a glyph silently dropped in the merge, a name
 * colliding, or a rendered SVG that breaks the shared contract every consumer
 * relies on (24×24 grid, currentColor, decorative by default).
 */
describe('the icon set', () => {
  it('exports exactly 88 icons', () => {
    /**
     * 52 from ToggleFlow + 55 from FixMyText, sharing 19 names. If this number
     * changes without a changeset, an icon was added or lost by accident.
     */
    expect(entries.length).toBe(88);
  });

  it('has no duplicate or case-colliding names', () => {
    const lower = entries.map(([n]) => n.toLowerCase());
    expect(new Set(lower).size).toBe(lower.length);
  });

  it('preserves every name both source sets used', () => {
    /**
     * The migration promise: no consumer has to rename an import. These are the
     * names that appeared in the two original files, spelled out so that
     * dropping one is a test failure rather than a runtime crash in a
     * downstream app.
     */
    const fromToggleFlow = [
      'MenuIcon',
      'MoonIcon',
      'SunIcon',
      'XIcon',
      'ChevronDownIcon',
      'ChevronRightIcon',
      'ChevronsUpDownIcon',
      'CheckIcon',
      'PlusIcon',
      'ArrowUpIcon',
      'PowerIcon',
      'TrendingUpIcon',
      'TargetIcon',
      'SlidersIcon',
      'GlobeIcon',
      'HistoryIcon',
      'UsersIcon',
      'SplitIcon',
      'AlertTriangleIcon',
      'SparklesIcon',
      'LayersIcon',
      'CircleCheckIcon',
      'CircleSlashIcon',
      'CircleHalfIcon',
      'DotIcon',
      'HomeIcon',
      'SearchIcon',
      'FlagIcon',
      'FilterIcon',
      'KeyIcon',
      'WebhookIcon',
      'PlugIcon',
      'CreditCardIcon',
      'BuildingIcon',
      'FolderIcon',
      'LogOutIcon',
      'UserIcon',
      'PanelLeftIcon',
      'ToggleMarkIcon',
      'MoreHorizontalIcon',
      'ArrowUpDownIcon',
      'ArrowDownIcon',
      'CopyIcon',
      'PencilIcon',
      'ArchiveIcon',
      'TrashIcon',
      'ToggleIcon',
      'ArrowRightIcon',
      'ClockIcon',
      'CodeIcon',
      'RotateCcwIcon',
      'UploadIcon',
    ];
    const fromFixMyText = [
      'AlertTriangleIcon',
      'ArrowRightIcon',
      'BarChart3Icon',
      'BotIcon',
      'CheckIcon',
      'ChevronDownIcon',
      'ChevronUpIcon',
      'ClockIcon',
      'CodeIcon',
      'CommandIcon',
      'CornerUpLeftIcon',
      'CornerUpRightIcon',
      'DownloadIcon',
      'DropletIcon',
      'EllipsisIcon',
      'FileTextIcon',
      'FlameIcon',
      'Gamepad2Icon',
      'GemIcon',
      'GiftIcon',
      'GraduationCapIcon',
      'GripVerticalIcon',
      'HeartIcon',
      'HistoryIcon',
      'KeyboardIcon',
      'LayoutGridIcon',
      'LayoutTemplateIcon',
      'LightbulbIcon',
      'LinkIcon',
      'LockIcon',
      'LockOpenIcon',
      'LogInIcon',
      'LogOutIcon',
      'MenuIcon',
      'MinusIcon',
      'MoonIcon',
      'PenLineIcon',
      'PlayIcon',
      'PlusIcon',
      'RotateCcwIcon',
      'SearchIcon',
      'ShieldIcon',
      'SmartphoneIcon',
      'SmileIcon',
      'SparklesIcon',
      'StarIcon',
      'SunIcon',
      'TargetIcon',
      'Trash2Icon',
      'TrendingUpIcon',
      'TrophyIcon',
      'UserIcon',
      'WrenchIcon',
      'XIcon',
      'ZapIcon',
    ];

    expect(new Set(fromToggleFlow).size).toBe(52);
    expect(new Set(fromFixMyText).size).toBe(55);

    const exported = new Set(entries.map(([n]) => n));
    const missing = [...new Set([...fromToggleFlow, ...fromFixMyText])].filter(
      (n) => !exported.has(n),
    );
    expect(missing, `names lost in the merge: ${missing.join(', ')}`).toEqual([]);
  });

  it('keeps TrashIcon and Trash2Icon as separate names', () => {
    /**
     * The two apps named the same concept differently. Both survive, because
     * renaming would break one consumer for no benefit.
     */
    expect(iconsModule).toHaveProperty('TrashIcon');
    expect(iconsModule).toHaveProperty('Trash2Icon');
  });
});

describe('every icon honours the shared contract', () => {
  for (const [name, Icon] of entries) {
    describe(name, () => {
      it('renders a 24×24-grid SVG at the default 16px', () => {
        const { container } = render(createElement(Icon));
        const svg = container.querySelector('svg')!;
        expect(svg).toBeTruthy();
        expect(svg.getAttribute('viewBox')).toBe('0 0 24 24');
        expect(svg.getAttribute('width')).toBe('16');
        expect(svg.getAttribute('height')).toBe('16');
      });

      it('inherits colour and never hardcodes a fill', () => {
        const { container } = render(createElement(Icon));
        const svg = container.querySelector('svg')!;
        expect(svg.getAttribute('stroke')).toBe('currentColor');
        expect(svg.getAttribute('fill')).toBe('none');
        // A literal colour anywhere inside would break theming silently.
        expect(svg.innerHTML).not.toMatch(/#[0-9a-f]{3,6}|rgba?\(/i);
      });

      it('is decorative by default', () => {
        const { container } = render(createElement(Icon));
        expect(container.querySelector('svg')!.getAttribute('aria-hidden')).toBe('true');
      });

      it('has drawable content', () => {
        const { container } = render(createElement(Icon));
        expect(container.querySelector('svg')!.children.length).toBeGreaterThan(0);
      });

      it('sets a displayName for readable component stacks', () => {
        expect((Icon as { displayName?: string }).displayName).toBe(name);
      });
    });
  }
});

describe('the accessibility opt-in', () => {
  it('honours a caller-supplied size', () => {
    const { container } = render(createElement(iconsModule.FlagIcon, { size: 24 }));
    const svg = container.querySelector('svg')!;
    expect(svg.getAttribute('width')).toBe('24');
    expect(svg.getAttribute('height')).toBe('24');
  });

  it('lets a caller clear aria-hidden to make an icon semantic', () => {
    const { container } = render(
      createElement(iconsModule.TrashIcon, {
        'aria-hidden': undefined,
        role: 'img',
        'aria-label': 'Delete',
      }),
    );
    const svg = container.querySelector('svg')!;
    expect(svg.hasAttribute('aria-hidden')).toBe(false);
    expect(svg.getAttribute('aria-label')).toBe('Delete');
  });

  it('documents the trap: aria-label alone stays hidden', () => {
    /**
     * Not an endorsement — an assertion that the failure mode is what the
     * docblock on `createIcon` says it is. `aria-hidden` wins over
     * `aria-label`, so the label is never announced.
     */
    const { container } = render(createElement(iconsModule.TrashIcon, { 'aria-label': 'Delete' }));
    expect(container.querySelector('svg')!.getAttribute('aria-hidden')).toBe('true');
  });

  it('forwards arbitrary SVG props and className', () => {
    /*
     * JSX rather than `createElement` here: React's SVGProps does not include an
     * index signature for `data-*`, so those attributes typecheck only through
     * JSX's own handling of them. The runtime behaviour is identical.
     */
    const { container } = render(<iconsModule.FlagIcon className="text-link" data-testid="x" />);
    const svg = container.querySelector('svg')!;
    expect(svg.getAttribute('class')).toBe('text-link');
    expect(svg.getAttribute('data-testid')).toBe('x');
  });
});

describe('createIcon', () => {
  it('is exported so apps can extend the set locally', () => {
    const Custom = createIcon('CustomIcon', createElement('circle', { cx: 12, cy: 12, r: 4 }));
    const { container } = render(createElement(Custom));
    expect(container.querySelector('circle')).toBeTruthy();
    expect(Custom.displayName).toBe('CustomIcon');
  });
});
