import {
  contrastRatio,
  dark,
  light,
  neutral,
  round2,
  seed,
  type SemanticTokens,
} from '@velobits-dev/tokens';
import { Badge } from '@velobits-dev/ui';

export const metadata = { title: 'Tokens — VeloBits UI' };

/**
 * Reads the token modules directly rather than restating any value, so this page
 * cannot drift from the palette. Every ratio shown is computed at build time by
 * the same functions the contrast test uses.
 */

function Swatch({ hex, name }: { hex: string; name: string }) {
  const opaque = /^#[0-9a-fA-F]{6}$/.test(hex);
  return (
    <div className="flex items-center gap-3">
      <div
        className="size-9 shrink-0 rounded-md border border-border"
        style={{ background: hex }}
        aria-hidden
      />
      <div className="min-w-0">
        <div className="truncate text-sm font-medium">{name}</div>
        <div className="font-mono text-xs text-muted-foreground">{hex}</div>
      </div>
      {!opaque && <Badge variant="outline">α</Badge>}
    </div>
  );
}

const PAIRS: [label: string, fg: keyof SemanticTokens, bg: keyof SemanticTokens, target: number][] =
  [
    ['body text on page', 'fg', 'bg', 4.5],
    ['muted text on page', 'mutedFg', 'bg', 4.5],
    ['link on page', 'primaryText', 'bg', 4.5],
    ['white on primary fill', 'onPrimary', 'primary', 4.5],
    ['charcoal on brand fill', 'onBrand', 'brand', 4.5],
    ['primary fill vs page', 'primary', 'bg', 3],
    ['focus ring vs page', 'ring', 'bg', 3],
    ['field border vs panel', 'fieldBorder', 'panel', 3],
  ];

export default function TokensPage() {
  return (
    <div className="space-y-12">
      <section>
        <h1 className="mt-8 mb-2 text-3xl font-semibold tracking-tight">Tokens</h1>
        <p className="text-muted-foreground">
          Every value below is read from <code>@velobits-dev/tokens</code> at build time. Nothing on
          this page is transcribed.
        </p>
      </section>

      <section>
        <h2 className="mb-4 text-xl font-semibold">Seeds</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Object.entries(seed).map(([name, hex]) => (
            <Swatch key={name} name={name} hex={hex} />
          ))}
        </div>
      </section>

      <section>
        <h2 className="mb-1 text-xl font-semibold">Warm neutral ramp</h2>
        <p className="mb-4 text-sm text-muted-foreground">
          Generated by holding cream&apos;s hue and decaying chroma toward the dark end, so a grey
          beside the brand cream never reads cold. <code>750</code> exists solely so the dark-mode
          border sits above <code>--panel</code>.
        </p>
        <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {Object.entries(neutral).map(([step, hex]) => (
            <Swatch key={step} name={`neutral-${step}`} hex={hex} />
          ))}
        </div>
      </section>

      <section>
        <h2 className="mb-4 text-xl font-semibold">Measured pairs</h2>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr>
                <th className="border-b border-border px-3 py-2 text-start">Pair</th>
                <th className="border-b border-border px-3 py-2 text-start">Target</th>
                <th className="border-b border-border px-3 py-2 text-start">Light</th>
                <th className="border-b border-border px-3 py-2 text-start">Dark</th>
              </tr>
            </thead>
            <tbody>
              {PAIRS.map(([label, fg, bg, target]) => {
                const l = round2(contrastRatio(light[fg], light[bg]));
                const d = round2(contrastRatio(dark[fg], dark[bg]));
                return (
                  <tr key={label}>
                    <td className="border-b border-border px-3 py-2">{label}</td>
                    <td className="border-b border-border px-3 py-2 text-muted-foreground">
                      ≥{target}:1
                    </td>
                    <td className="border-b border-border px-3 py-2">
                      <Badge variant={l >= target ? 'success' : 'danger'}>{l}:1</Badge>
                    </td>
                    <td className="border-b border-border px-3 py-2">
                      <Badge variant={d >= target ? 'success' : 'danger'}>{d}:1</Badge>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
