import * as iconModule from '@velobits-dev/icons';
import { type Icon as IconComponent } from '@velobits-dev/icons';

import { Group, Section } from '../section';

export const metadata = { title: 'Icons — VeloBits UI' };

/**
 * The icon gallery.
 *
 * Until this page existed, `@velobits-dev/icons` shipped 88 glyphs and the docs
 * app rendered 18 of them — all incidental, sitting inside component demos on
 * `/components`. Seventy were published with no way to see them, and `createIcon`
 * was public API documented only in a CHANGELOG.
 *
 * ## It enumerates the module, not a list
 *
 * `import * as iconModule` and filter, using the same predicate `icons.test.tsx`
 * uses. A 89th icon appears here the moment it is exported; nobody edits this
 * file. The alternative — a literal array of names — is precisely the drift the
 * `/tokens` rebuild was undertaken to remove, and at 88 entries it would be
 * worse, because a single missing name is invisible in a grid this size.
 *
 * `createIcon` has to be excluded by name rather than by shape: it is a function
 * whose name ends in `Icon`, so a bare `endsWith('Icon')` counts 89. That is the
 * same off-by-one an unanchored `grep -c "export const \w+Icon"` produces.
 *
 * ## No blur here
 *
 * SiteHeader's sticky `.glass` is the only blurred layer on this route. The
 * swatch cells are dashed hairlines on the page background, matching `Demo` —
 * see the docblock in `app/section.tsx` for why a demo frame is never `--panel`.
 */

/**
 * The same filter `packages/icons/test/icons.test.tsx` asserts 88 against.
 *
 * The predicate narrows to the package's own `Icon` type rather than a
 * hand-written `(props: IconProps) => ReactElement`. That signature looks
 * equivalent and is not: `createIcon` attaches a `displayName`, so `Icon`
 * requires it and a bare call signature fails to satisfy the narrowing.
 */
const ICONS = Object.entries(iconModule)
  .filter(
    (entry): entry is [string, IconComponent] =>
      entry[0].endsWith('Icon') && entry[0] !== 'createIcon' && typeof entry[1] === 'function',
  )
  .sort(([a], [b]) => a.localeCompare(b));

/** The range the geometry was drawn for, per `createIcon`'s sizing contract. */
const SIZES = [13, 14, 16, 18, 24] as const;

function Swatch({ name, Icon }: { name: string; Icon: IconComponent }) {
  return (
    <div className="flex flex-col items-center gap-2 rounded-lg border border-dashed border-border p-3">
      <Icon size={20} />
      <code className="w-full truncate text-center text-[11px] text-muted-foreground" title={name}>
        {name.replace(/Icon$/, '')}
      </code>
    </div>
  );
}

export default function IconsPage() {
  return (
    <div className="space-y-16">
      <div className="mt-8">
        <h1 className="mb-2 text-3xl font-semibold tracking-tight">Icons</h1>
        <p className="max-w-3xl text-muted-foreground">
          All {ICONS.length} of them, hand-drawn on a 24×24 grid and tuned to read at 13–18px. This
          grid is generated by enumerating the package, so an icon added to{' '}
          <code>@velobits-dev/icons</code> appears here without anyone editing this page.
        </p>
      </div>

      <Group
        title={`The set — ${ICONS.length} icons`}
        note="Names are shown without their Icon suffix; the import is the name plus Icon — trash is TrashIcon. Every glyph uses stroke=currentColor, so it inherits the colour of whatever it sits in."
      >
        <div className="grid grid-cols-3 gap-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8">
          {ICONS.map(([name, Icon]) => (
            <Swatch key={name} name={name} Icon={Icon} />
          ))}
        </div>
      </Group>

      <Group
        title="Using them"
        note="Three things about this package that are easy to get wrong, each of them load-bearing."
      >
        <Section
          title="Sizing"
          note="size sets both width and height, and is preferred over Tailwind's size-* utilities: the rendered attribute then matches the size the geometry was tuned for. Scaling a 16px glyph with a class is fine; scaling a 24px one is not."
        >
          <div className="flex flex-wrap items-end gap-6 rounded-xl border border-dashed border-border p-6">
            {SIZES.map((size) => (
              <div key={size} className="flex flex-col items-center gap-2">
                <iconModule.FlagIcon size={size} />
                <code className="text-xs text-muted-foreground">{size}px</code>
              </div>
            ))}
          </div>
        </Section>

        <Section
          title="Decorative by default"
          note="Icons render aria-hidden=true, because most sit beside a text label that already names the action. An icon carrying meaning alone has to opt out explicitly — and passing aria-label on its own is not enough, since aria-hidden wins and the label is never announced."
        >
          <div className="rounded-xl border border-dashed border-border p-6">
            <pre className="overflow-x-auto font-mono text-xs">
              <code>{`// decorative — the label beside it does the work
<TrashIcon /> Delete

// meaningful on its own — all three props are required
<TrashIcon aria-hidden={undefined} role="img" aria-label="Delete flag" />`}</code>
            </pre>
          </div>
        </Section>

        <Section
          title="createIcon"
          note="Exported for one-off glyphs that need the same geometry — a 24×24 grid, currentColor, strokeWidth 2, round caps and joins, and a default size of 16. Anything reused across surfaces belongs in the package instead."
        >
          <div className="rounded-xl border border-dashed border-border p-6">
            <pre className="overflow-x-auto font-mono text-xs">
              <code>{`import { createIcon } from '@velobits-dev/icons';

export const PentagonIcon = createIcon(
  'PentagonIcon',
  <path d="M12 3l9 6.5-3.5 10.5h-11L3 9.5z" />,
);`}</code>
            </pre>
          </div>
        </Section>
      </Group>
    </div>
  );
}
