import type { Metadata } from 'next';

import { FlagIcon } from '@velobitsio/icons';
/*
 * The SUBPATH, not the barrel. This is a Server Component: rendering a client
 * component from here is fine, but pulling the whole `'use client'` barrel in to
 * get one of them would ship every component in the library to this page's client
 * bundle. `./code-block` is its own tsup entry for exactly this.
 */
import { CodeBlock } from '@velobitsio/ui/code-block';

import { DocsToc, type TocEntry } from '@/components/docs-toc';
import { Group, Section } from '@/components/docs-section';

import { IconGrid } from './icon-grid';
import { ICON_COUNT } from './icons-data';

export const metadata: Metadata = {
  title: 'Icons',
  description: 'Hand-drawn stroke icons on a 24×24 grid, tuned to read at 13–18px.',
};

/*
 * The two prose snippets on this page, each offered in both languages.
 *
 * ⚠️ Both entries carry the SAME string, and that is the point rather than an
 * oversight: these are JSX and an import line, so there is no type annotation for
 * a transform to strip and the JavaScript rendering is character-for-character the
 * TypeScript one. The label is still what the reader came for , "usable as-is in
 * JavaScript" is an answer, and an absent control is not. Same call as the docs'
 * Usage snippets and the icon dialog's JSX tab.
 *
 * Written out rather than derived because there is no build step in reach: these
 * are string literals in a `.tsx` file, and `scripts/build-guide-code.ts` scans
 * `.mdx` fences.
 */
const DECORATIVE_CODE = `// decorative: the label beside it does the work
<TrashIcon /> Delete

// meaningful on its own: all three props are required
<TrashIcon aria-hidden={undefined} role="img" aria-label="Delete flag" />`;

const CREATE_ICON_CODE = `import { createIcon } from '@velobitsio/icons';

export const PentagonIcon = createIcon(
  'PentagonIcon',
  <path d="M12 3l9 6.5-3.5 10.5h-11L3 9.5z" />,
);`;

const DECORATIVE_SNIPPET = [
  { language: 'ts', code: DECORATIVE_CODE },
  { language: 'js', code: DECORATIVE_CODE },
];

const CREATE_ICON_SNIPPET = [
  { language: 'ts', code: CREATE_ICON_CODE },
  { language: 'js', code: CREATE_ICON_CODE },
];

/** The range the geometry was drawn for, per `createIcon`'s sizing contract. */
const SIZES = [13, 14, 16, 18, 24] as const;

const TOC: TocEntry[] = [
  { id: 'the-set', title: 'The set', level: 2 },
  { id: 'using-them', title: 'Using them', level: 2 },
  { id: 'sizing', title: 'Sizing', level: 3 },
  { id: 'decorative', title: 'Decorative by default', level: 3 },
  { id: 'create-icon', title: 'createIcon', level: 3 },
];

/**
 * The icon gallery.
 *
 * Until this page existed, `@velobitsio/icons` shipped 88 glyphs and the docs
 * app rendered 18 of them , all incidental, sitting inside component demos.
 * Seventy were published with no way to see them, and `createIcon` was public API
 * documented only in a CHANGELOG.
 *
 * No blur here: the SiteHeader's sticky `.glass` is the only blurred layer on
 * this route. The swatch cells are dashed hairlines on the page background,
 * matching every other frame on the site.
 */
export default function IconsPage() {
  return (
    <div className="xl:grid xl:grid-cols-[minmax(0,1fr)_14rem] xl:gap-10">
      <main id="main" className="min-w-0 space-y-12 py-8 pb-24">
        <header className="space-y-3">
          <h1 className="text-3xl font-semibold tracking-tight">Icons</h1>
          <p className="max-w-3xl leading-7 text-muted-foreground">
            All {ICON_COUNT} of them, hand-drawn on a 24×24 grid and tuned to read at 13–18px. This
            grid is generated by enumerating the package, so an icon added to{' '}
            <code>@velobitsio/icons</code> appears here without anyone editing this page.
          </p>
        </header>

        <Group
          id="the-set"
          title={`The set: ${ICON_COUNT} icons`}
          note="Names are shown without their Icon suffix; the import is the name plus Icon, so trash is TrashIcon. Every glyph uses stroke=currentColor, so it inherits the colour of whatever it sits in."
        >
          <IconGrid />
        </Group>

        <Group
          id="using-them"
          title="Using them"
          note="Three things about this package that are easy to get wrong, each of them load-bearing."
        >
          <Section
            id="sizing"
            title="Sizing"
            note="size sets both width and height, and is preferred over Tailwind's size-* utilities: the rendered attribute then matches the size the geometry was tuned for. Scaling a 16px glyph with a class is fine; scaling a 24px one is not."
          >
            <div className="flex flex-wrap items-end gap-6 rounded-xl border border-dashed border-border p-6">
              {SIZES.map((size) => (
                <div key={size} className="flex flex-col items-center gap-2">
                  <FlagIcon size={size} />
                  <code className="text-xs text-muted-foreground">{size}px</code>
                </div>
              ))}
            </div>
          </Section>

          <Section
            id="decorative"
            title="Decorative by default"
            note="Icons render aria-hidden=true, because most sit beside a text label that already names the action. An icon carrying meaning alone has to opt out explicitly, and passing aria-label on its own is not enough, since aria-hidden wins and the label is never announced."
          >
            <div className="rounded-xl border border-dashed border-border p-6">
              <CodeBlock
                variants={DECORATIVE_SNIPPET}
                blockId="icons:decorative"
                copyable
                label="decorative vs meaningful icons"
                className="[&_pre]:border-0 [&_pre]:bg-transparent [&_pre]:p-0 [&_pre]:shadow-none [&_pre]:pt-12"
              />
            </div>
          </Section>

          <Section
            id="create-icon"
            title="createIcon"
            note="Exported for one-off glyphs that need the same geometry: a 24×24 grid, currentColor, strokeWidth 2, round caps and joins, and a default size of 16. Anything reused across surfaces belongs in the package instead."
          >
            <div className="rounded-xl border border-dashed border-border p-6">
              <CodeBlock
                variants={CREATE_ICON_SNIPPET}
                blockId="icons:create-icon"
                copyable
                label="createIcon"
                className="[&_pre]:border-0 [&_pre]:bg-transparent [&_pre]:p-0 [&_pre]:shadow-none [&_pre]:pt-12"
              />
            </div>
          </Section>
        </Group>
      </main>

      <aside className="hidden xl:sticky xl:top-14 xl:block xl:h-[calc(100dvh-3.5rem)] xl:overflow-y-auto xl:py-8">
        <DocsToc entries={TOC} />
      </aside>
    </div>
  );
}
