/**
 * Derives the language variants for fenced code blocks in the MDX guides, and
 * highlights them.
 *
 * Run: `npm run docs:data` , this runs alongside `build-docs-data.ts`, which owns
 * the component pages. The split is not arbitrary: that script's inputs are
 * `registry/registry.ts` and TypeScript sources it can read directly, while this
 * one's inputs are `.mdx` files whose code blocks belong to Next's compiler. The
 * two never share a parse, so sharing a script would only share a filename.
 *
 * Writes `apps/docs/lib/generated/guide-code.ts`: a map from a content hash to
 * that block's variants. See `apps/docs/lib/guide-code-key.ts` for why the key is
 * a hash of the code rather than a file and line , the short version is that MDX
 * gives element overrides no position information, so content is the only thing
 * the build and the renderer both hold.
 *
 * ## Why this exists at all
 *
 * Two reasons, and the second was a surprise.
 *
 * The first is the feature: a `tsx` block in a guide should offer JavaScript, the
 * same as a component page's example does, and a reader should not have to notice
 * which kind of page they are on.
 *
 * The second is that **the guide blocks were never highlighted**. The `pre`
 * override in `mdx-components.tsx` styled them and stopped there, so eighteen
 * shell commands, four CSS snippets and three JSON blobs shipped as grey text
 * while every component page had Shiki. Nobody filed it, which is the usual fate
 * of a gap that looks like a decision. Since this script already has to highlight
 * the TypeScript half, extending it to every labelled fence costs one branch.
 *
 * ## What is deliberately left alone
 *
 * Three fences in the guides carry no language , two shadcn prompt transcripts
 * and the `components/ui/velobits/` tree listing. They are terminal output, not
 * code in any language, and they emit nothing here: the renderer finds no entry
 * and falls back to the plain `<pre>` it has always rendered. A selector on a
 * transcript would be a control with one option, and highlighting one is inventing
 * syntax it does not have.
 */
import { readdirSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { codeToHtml } from 'shiki';

import { guideCodeKey, normalizeGuideCode } from '../apps/docs/lib/guide-code-key.ts';
import { tsToJs } from './code-transform.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = join(root, 'apps/docs');
const guidesDir = join(docsDir, 'app');
const outDir = join(docsDir, 'lib/generated');
const outFile = join(outDir, 'guide-code.ts');

const BANNER = `/* GENERATED by scripts/build-guide-code.ts , do not edit, do not commit. */\n`;

/**
 * How a fence's info string maps onto the language registry.
 *
 * Keyed by what an author actually writes after the backticks, valued with the
 * `CODE_LANGUAGES` id in `registry/velobits/lib/code-languages.ts` plus the Shiki
 * grammar to highlight it with. Kept as a table rather than derived from the
 * registry because the registry is keyed by language *id* and this is keyed by
 * *fence label*, and the two are not the same mapping , `tsx` and `ts` are both
 * the `ts` language here, which is the whole point.
 *
 * An unlisted label emits nothing at all. That is the safe direction: a guide
 * gains a language by adding a line here, and until someone does, the block
 * renders exactly as it did before this script existed.
 */
const FENCE_LANGUAGES: Record<string, { language: string; grammar: string }> = {
  tsx: { language: 'ts', grammar: 'tsx' },
  ts: { language: 'ts', grammar: 'tsx' },
  typescript: { language: 'ts', grammar: 'tsx' },
  jsx: { language: 'js', grammar: 'jsx' },
  js: { language: 'js', grammar: 'jsx' },
  javascript: { language: 'js', grammar: 'jsx' },
  css: { language: 'css', grammar: 'css' },
  json: { language: 'json', grammar: 'json' },
  bash: { language: 'bash', grammar: 'bash' },
  sh: { language: 'bash', grammar: 'bash' },
  shell: { language: 'bash', grammar: 'bash' },
  html: { language: 'html', grammar: 'html' },
  md: { language: 'md', grammar: 'markdown' },
  markdown: { language: 'md', grammar: 'markdown' },
};

/** Which fence labels get a mechanically-derived JavaScript sibling. */
const DERIVES_JS = new Set(['tsx', 'ts', 'typescript']);

/**
 * Same options as `build-docs-data.ts`: one payload serving both themes.
 *
 * `defaultColor: false` makes Shiki emit `--shiki-light` and `--shiki-dark` per
 * token rather than a baked colour, and `app/globals.css` picks between them off
 * the `dark` class. Highlighting twice and hiding one would double the bytes to
 * show the same characters.
 */
async function highlight(code: string, grammar: string): Promise<string> {
  return codeToHtml(code, {
    lang: grammar,
    themes: { light: 'github-light', dark: 'github-dark' },
    defaultColor: false,
  });
}

/** Every `page.mdx` under `apps/docs/app`, depth-first. */
function findGuides(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...findGuides(path));
    else if (entry.name.endsWith('.mdx')) found.push(path);
  }
  return found.sort();
}

interface Fence {
  file: string;
  line: number;
  label: string;
  code: string;
}

/**
 * Pull the fenced blocks out of one MDX file.
 *
 * A line-based toggle rather than a Markdown parser, which is honest about what
 * it can and cannot do: it would mis-read a fence nested inside another fence.
 * The guides contain none, and the `unbalanced` check below is what stops that
 * assumption rotting quietly , if someone ever writes one, this fails the build
 * instead of silently swallowing half a page.
 */
function readFences(file: string): { fences: Fence[]; unbalanced: boolean } {
  const lines = readFileSync(file, 'utf8').split('\n');
  const fences: Fence[] = [];
  let open: { line: number; label: string; body: string[] } | null = null;

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    if (!line.startsWith('```')) {
      if (open) open.body.push(line);
      continue;
    }
    if (open) {
      fences.push({
        file,
        line: open.line,
        label: open.label,
        code: normalizeGuideCode(open.body.join('\n')),
      });
      open = null;
    } else {
      open = { line: i + 1, label: line.slice(3).trim().split(/\s+/)[0] ?? '', body: [] };
    }
  }

  return { fences, unbalanced: open !== null };
}

/* ── Scan ──────────────────────────────────────────────────────────────────── */

const guides = findGuides(guidesDir);
const fences: Fence[] = [];
let unbalanced = false;

for (const file of guides) {
  const result = readFences(file);
  if (result.unbalanced) {
    console.error(
      `\n${relative(root, file)} has an unclosed \`\`\` fence. ` +
        `This script reads fences by toggling on every line that starts with three ` +
        `backticks, so an unclosed one swallows the rest of the page.`,
    );
    unbalanced = true;
  }
  fences.push(...result.fences);
}

if (unbalanced) process.exit(1);

/* ── Derive and highlight ──────────────────────────────────────────────────── */

interface Variant {
  language: string;
  code: string;
  html: string;
}

const entries = new Map<string, { variants: Variant[]; from: Fence }>();
let skipped = 0;
let derived = 0;
const skippedJs: string[] = [];

for (const fence of fences) {
  const mapping = FENCE_LANGUAGES[fence.label];
  if (!fence.label || !mapping || !fence.code) {
    skipped += 1;
    continue;
  }

  const key = guideCodeKey(fence.code);
  const existing = entries.get(key);
  if (existing) {
    /*
     * Same key, same code is the intended sharing , two guides showing the same
     * snippet get one entry. Same key, DIFFERENT code is a hash collision, and it
     * would make one page render the other's code. See `guide-code-key.ts` for why
     * that is close to impossible; this is here so that "close to" is not load
     * bearing.
     */
    if (existing.variants[0].code !== fence.code) {
      console.error(
        `\nHash collision on guide code key ${key}:\n` +
          `  ${relative(root, existing.from.file)}:${existing.from.line}\n` +
          `  ${relative(root, fence.file)}:${fence.line}\n` +
          `Two different blocks hash alike, so one page would render the other's code.`,
      );
      process.exit(1);
    }
    continue;
  }

  const variants: Variant[] = [
    {
      language: mapping.language,
      code: fence.code,
      html: await highlight(fence.code, mapping.grammar),
    },
  ];

  /*
   * The TypeScript half gets a JavaScript sibling, and it goes SECOND , the
   * block's own language stays the default, which is what makes "keep the current
   * language as the default" a property of ordering rather than a special case
   * anywhere in the renderer.
   */
  if (DERIVES_JS.has(fence.label)) {
    /*
     * `tsToJs` returns `null` when there is no meaningful JavaScript variant to
     * show, and deciding that is ITS job, not ours , see `code-transform.ts` for
     * the four cases and why each one exists. Three of them were found on this
     * repository's own guides rather than reasoned about in advance, and one of
     * them (a pair of sibling JSX elements re-printed as a comma-sequence
     * expression) produced output that was wrong while looking entirely plausible.
     *
     * Keeping the policy in one place matters because there are two callers: this
     * script and `build-docs-data.ts`. A guide block and a component page's usage
     * snippet must not disagree about whether a language exists.
     */
    const js = await tsToJs(fence.code, `${relative(root, fence.file)}:${fence.line}.tsx`);
    if (js === null) {
      skippedJs.push(`${relative(root, fence.file)}:${fence.line}`);
    } else {
      const code = normalizeGuideCode(js.code);
      variants.push({ language: 'js', code, html: await highlight(code, 'jsx') });
      derived += 1;
    }
  }

  entries.set(key, { variants, from: fence });
}

/* ── Emit ──────────────────────────────────────────────────────────────────── */

mkdirSync(outDir, { recursive: true });

const emitted = Object.fromEntries(
  [...entries.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, v]) => [key, v.variants]),
);

writeFileSync(
  outFile,
  BANNER +
    `\n` +
    `/** One rendering of a guide's fenced block, in one language. */\n` +
    `export interface GuideCodeVariant {\n` +
    `  /** A \`CODE_LANGUAGES\` id: 'ts' | 'js' | 'css' | 'json' | 'bash' | … */\n` +
    `  language: string;\n` +
    `  /** The literal code, for the copy button. */\n` +
    `  code: string;\n` +
    `  /** Shiki markup for \`code\`, built at build time. */\n` +
    `  html: string;\n` +
    `}\n\n` +
    `/**\n` +
    ` * Keyed by \`guideCodeKey(code)\`. The FIRST variant is the block's own\n` +
    ` * language and therefore the default; any others are derived siblings.\n` +
    ` */\n` +
    `export const guideCode: Record<string, GuideCodeVariant[]> = ${JSON.stringify(
      emitted,
      null,
      2,
    )};\n`,
  'utf8',
);

const bytes = Buffer.byteLength(readFileSync(outFile));
console.log(
  `guide-code.ts  ${entries.size} block(s) from ${guides.length} guide(s), ` +
    `${derived} with a derived JS variant, ${skipped} unlabelled/skipped, ` +
    `${(bytes / 1024).toFixed(1)} kB`,
);

/*
 * Named, not counted. A skipped JS variant is a block that silently has one fewer
 * language than the reader might expect, and the whole reason the degenerate case
 * got as far as a generated file is that nothing said it had happened.
 */
if (skippedJs.length) {
  console.log(`               no JS variant for ${skippedJs.length}: ${skippedJs.join(', ')}`);
}
