/**
 * Generates everything the docs site knows about itself, from the two things
 * that are already true: `registry/registry.ts` and the TypeScript sources.
 *
 * Run: `npm run docs:data` , but you rarely need to. `apps/docs`'s `dev` and
 * `build` scripts both run it first, so a clean clone never sees the output
 * missing, and the output is gitignored precisely so it cannot go stale.
 *
 * Writes into `apps/docs/lib/generated/`:
 *
 *   examples.ts       every file in `apps/docs/registry/examples/` as both a
 *                     component (for the Preview tab) and its literal source
 *                     (for the Code tab)
 *   registry-data.ts  each registry item's metadata plus the source of the files
 *                     it installs, for the Manual install tab
 *   props.ts          prop tables extracted from the TypeScript types
 *
 * and `apps/docs/public/search-index.json` for ⌘K.
 *
 * ## Why generate rather than read at render time
 *
 * The site is a static export, so a Server Component *could* just `readFileSync`
 * during the build and get the same bytes. Generating first buys two things that
 * matter more than the indirection costs: the parse happens once for ~90 files
 * instead of once per page that mentions them, and `tsc --noEmit` type-checks the
 * result , a renamed example is a type error in `apps/docs`, not a blank preview
 * discovered by looking at the deployed page.
 *
 * ## ⚠️ The generated files must stay out of Tailwind's scan
 *
 * They embed component sources as JSON-escaped string literals. Tailwind scans
 * plain text, so a `"` that a component legitimately has inside an arbitrary
 * value arrives as `\"`, and Lightning CSS rejects the resulting declaration as
 * `BadUrl` , taking the whole stylesheet down with a 500 rather than dropping one
 * rule. `app/globals.css` carries the matching `@source not` lines. This is the
 * same failure that already forced one for `public/r`.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { withCustomConfig, type PropItem } from 'react-docgen-typescript';
import { codeToHtml } from 'shiki';
import ts from 'typescript';

import { registry } from '../registry/registry.ts';
import { COMPONENT_CONTENT } from '../apps/docs/content/components.ts';
import { COMPONENT_GROUPS, GROUPED_COMPONENT_NAMES, GUIDE_NAV } from '../apps/docs/lib/docs-nav.ts';
import { displayTarget, importSpecifierFor, targetFor } from './registry-layout.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = join(root, 'apps/docs');
const examplesDir = join(docsDir, 'registry/examples');
const outDir = join(docsDir, 'lib/generated');

const BANNER = `/* GENERATED by scripts/build-docs-data.ts , do not edit, do not commit. */\n`;

mkdirSync(outDir, { recursive: true });

/* ── Syntax highlighting, at BUILD time ────────────────────────────────────── */

/**
 * Shiki runs here and ships HTML, so the browser downloads no highlighter and no
 * grammar , which for a static site is the difference between a code tab that
 * paints with the page and one that flashes plain text first.
 *
 * `defaultColor: false` is what makes one string serve both themes: Shiki emits
 * `--shiki-light` and `--shiki-dark` custom properties per token instead of a
 * baked-in colour, and `app/globals.css` picks between them off the `dark` class.
 * The alternative , highlighting twice and hiding one , doubles the payload to
 * show the same characters.
 */
async function highlight(code: string, lang: string): Promise<string> {
  return codeToHtml(code, {
    lang,
    themes: { light: 'github-light', dark: 'github-dark' },
    defaultColor: false,
  });
}

/* ── 0. The sidebar must place every registry item ─────────────────────────── */

/**
 * `apps/docs/lib/docs-nav.ts` is the one hand-maintained list in the docs, and
 * this is what stops it drifting. The tiers live as section comments inside
 * `registry/registry.ts`, so there is no exported structure to derive them from
 * , but an unplaced item is a component with a page nobody can navigate to, and
 * that is exactly the kind of gap that survives review. So it fails the build,
 * by name.
 */
const registryNames = registry.items.map((i) => i.name);
const ungrouped = registryNames.filter((n) => !GROUPED_COMPONENT_NAMES.includes(n));
const phantom = GROUPED_COMPONENT_NAMES.filter((n) => !registryNames.includes(n));

if (ungrouped.length || phantom.length) {
  if (ungrouped.length) {
    console.error(
      `\napps/docs/lib/docs-nav.ts places no group for ${ungrouped.length} registry item(s):\n  ` +
        ungrouped.join('\n  ') +
        '\nEach one still gets a page at /docs/components/<name>, but nothing in the sidebar links to it.',
    );
  }
  if (phantom.length) {
    console.error(
      `\napps/docs/lib/docs-nav.ts lists ${phantom.length} name(s) that are not in the registry:\n  ` +
        phantom.join('\n  ') +
        '\nThese would render as 404s from the sidebar.',
    );
  }
  process.exit(1);
}

/* ── The CLI variant of an example ─────────────────────────────────────────── */

/**
 * Which installed file each exported name comes from.
 *
 * The npm package has a barrel, so an example imports `{ Card, CardHeader }` from
 * `@velobitsio/ui` in one line. The CLI installs one file per component and no
 * barrel at all, so the same example is several import lines, and which line a
 * name belongs on is decided by the registry item that exports it.
 *
 * Parsed from the sources rather than listed, for the same reason the icon grid
 * enumerates its module: a hand-kept table of 215 exports is a table that goes
 * stale, and the failure is silent because a wrong import still renders here.
 */
const ownerOf = new Map<string, string>();
for (const item of registry.items) {
  for (const file of item.files ?? []) {
    const src = readFileSync(join(root, file.path), 'utf8');
    const names = new Set<string>();
    const declared = /^export\s+(?:const|function|class|interface|type|enum)\s+([A-Za-z0-9_]+)/gm;
    for (const m of src.matchAll(declared)) names.add(m[1]);
    for (const m of src.matchAll(/^export\s*\{([^}]+)\}/gm)) {
      for (const part of m[1].split(',')) {
        const name = part
          .trim()
          .split(/\s+as\s+/)
          .pop()
          ?.trim()
          .replace(/^type\s+/, '');
        if (name) names.add(name);
      }
    }
    for (const name of names) if (!ownerOf.has(name)) ownerOf.set(name, file.path);
  }
}

/** One import line, wrapped the way Prettier would wrap it at 100 columns. */
function importLine(specifier: string, names: string[], typeOnly: boolean): string {
  const kind = typeOnly ? 'import type' : 'import';
  const oneLine = `${kind} { ${names.join(', ')} } from '${specifier}';`;
  if (oneLine.length <= 100) return oneLine;
  const body = names.map((n) => `  ${n},`).join('\n');
  return `${kind} {\n${body}\n} from '${specifier}';`;
}

/**
 * Rewrites an example's `@velobitsio/ui` imports into the per-file imports a CLI
 * consumer writes, and leaves every other import alone.
 *
 * `@velobitsio/icons` and `@velobitsio/tokens` deliberately survive untouched: the
 * registry items declare those two as npm DEPENDENCIES, so a CLI consumer installs
 * them from npm and imports them exactly as an npm consumer does. Rewriting them
 * would describe an install that never happens.
 *
 * Returns null when a name cannot be attributed to a file, which the caller turns
 * into a build failure. The alternative is an example shown with a stale import,
 * and since nothing in this repo compiles the installed output, nothing else would
 * catch it.
 */
function toCliSource(source: string): string | null {
  let unresolved: string | null = null;

  const barrel = /^import\s+(type\s+)?\{([^}]+)\}\s+from\s+'@velobitsio\/ui(?:\/[a-z-]+)?';$/gm;

  const out = source.replace(barrel, (line, typeOnly: string | undefined, inner: string) => {
    const groups = new Map<string, string[]>();
    for (const raw of inner.split(',')) {
      const spec = raw.trim();
      if (!spec) continue;
      const isType = /^type\s+/.test(spec);
      const bare = spec.replace(/^type\s+/, '');
      const name = bare.split(/\s+as\s+/)[0].trim();
      const path = ownerOf.get(name);
      if (!path) {
        unresolved = name;
        return line;
      }
      const specifier = importSpecifierFor(path);
      if (!groups.has(specifier)) groups.set(specifier, []);
      groups.get(specifier)!.push(typeOnly || !isType ? bare : `type ${bare}`);
    }
    return [...groups.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([specifier, names]) => importLine(specifier, names.sort(), Boolean(typeOnly)))
      .join('\n');
  });

  if (unresolved) {
    console.error(
      `${unresolved} is imported from '@velobitsio/ui' by an example, but no registry item exports it, so the CLI tab cannot say which file it comes from`,
    );
    return null;
  }
  return out;
}

/* ── 1. Examples ───────────────────────────────────────────────────────────── */

const exampleFiles = existsSync(examplesDir)
  ? readdirSync(examplesDir)
      .filter((f) => f.endsWith('.tsx'))
      .sort()
  : [];

if (!exampleFiles.length) {
  console.error(`no examples found in ${examplesDir} , every Preview tab would be empty`);
  process.exit(1);
}

const exampleImports: string[] = [];
const exampleEntries: string[] = [];

for (const [index, file] of exampleFiles.entries()) {
  const name = file.replace(/\.tsx$/, '');
  const source = readFileSync(join(examplesDir, file), 'utf8').trimEnd();
  const ident = `Example${index}`;

  // A path alias rather than a relative one: this file lives in `lib/generated`,
  // and `../../registry/examples/x` is only correct while it stays there.
  exampleImports.push(`import ${ident} from '@/registry/examples/${name}';`);

  // The same example as a CLI consumer would write it. A null here is a real
  // failure rather than a missing nicety: it means an example imports something
  // no registry item exports, so one of the two distributions cannot run it.
  const cliSource = toCliSource(source);
  if (cliSource === null) {
    console.error(`could not build the CLI import variant of ${file}`);
    process.exit(1);
  }
  exampleEntries.push(
    `  ${JSON.stringify(name)}: {\n` +
      `    name: ${JSON.stringify(name)},\n` +
      `    Component: ${ident},\n` +
      `    source: ${JSON.stringify(source)},\n` +
      `    html: ${JSON.stringify(await highlight(source, 'tsx'))},\n` +
      `    sourceCli: ${JSON.stringify(cliSource)},\n` +
      `    htmlCli: ${JSON.stringify(await highlight(cliSource, 'tsx'))},\n` +
      `  },`,
  );
}

writeFileSync(
  join(outDir, 'examples.ts'),
  BANNER +
    `import type { ComponentType } from 'react';\n\n` +
    exampleImports.join('\n') +
    `\n\nexport interface DocExample {\n` +
    `  name: string;\n` +
    `  Component: ComponentType;\n` +
    `  /** The literal source, for the copy button. */\n` +
    `  source: string;\n` +
    `  /** The same source, highlighted at build time. */\n` +
    `  html: string;\n` +
    `  /** The same example, importing the per-file paths the shadcn CLI installs. */\n` +
    `  sourceCli: string;\n` +
    `  /** The CLI variant, highlighted at build time. */\n` +
    `  htmlCli: string;\n` +
    `}\n\n` +
    `export const examples: Record<string, DocExample> = {\n` +
    exampleEntries.join('\n') +
    `\n};\n`,
  'utf8',
);

/* ── 2. Registry metadata + installable sources ────────────────────────────── */

interface EmittedFile {
  path: string;
  /** Where the shadcn CLI lands it in a consumer's tree. */
  target: string;
  source: string;
  html: string;
}

interface EmittedItem {
  name: string;
  type: string;
  title: string;
  description: string;
  group: string;
  dependencies: string[];
  devDependencies: string[];
  registryDependencies: string[];
  files: EmittedFile[];
}

/**
 * Where the CLI writes each file, spelled with the default aliases so it reads as
 * an instruction. Derived from `scripts/registry-layout.ts` , the same module
 * `build-registry.ts` stamps the real targets from, so the path in the docs cannot
 * disagree with the path the CLI uses.
 */
function installTarget(path: string): string {
  return displayTarget(targetFor(path));
}

const groupOf = new Map<string, string>();
for (const group of COMPONENT_GROUPS) {
  for (const name of group.names) groupOf.set(name, group.title);
}

const emittedItems: EmittedItem[] = [];
for (const item of registry.items) {
  const files: EmittedFile[] = [];
  for (const file of item.files ?? []) {
    const source = readFileSync(join(root, file.path), 'utf8').trimEnd();
    files.push({
      path: file.path,
      target: file.target ?? installTarget(file.path),
      source,
      html: await highlight(source, file.path.endsWith('.tsx') ? 'tsx' : 'ts'),
    });
  }

  emittedItems.push({
    name: item.name,
    type: item.type,
    title: item.title ?? item.name,
    description: item.description ?? '',
    group: groupOf.get(item.name) ?? 'Other',
    dependencies: [...(item.dependencies ?? [])],
    devDependencies: [...(item.devDependencies ?? [])],
    registryDependencies: [...(item.registryDependencies ?? [])],
    files,
  });
}

writeFileSync(
  join(outDir, 'registry-data.ts'),
  BANNER +
    `export interface DocRegistryFile {\n` +
    `  path: string;\n` +
    `  /** Where the shadcn CLI lands it in a consumer's tree. */\n` +
    `  target: string;\n` +
    `  source: string;\n` +
    `  /** The same source, highlighted at build time. */\n` +
    `  html: string;\n` +
    `}\n\n` +
    `export interface DocRegistryItem {\n` +
    `  name: string;\n` +
    `  type: string;\n` +
    `  title: string;\n` +
    `  description: string;\n` +
    `  group: string;\n` +
    `  dependencies: string[];\n` +
    `  devDependencies: string[];\n` +
    `  registryDependencies: string[];\n` +
    `  files: DocRegistryFile[];\n` +
    `}\n\n` +
    `export const registryItems: DocRegistryItem[] = ${JSON.stringify(emittedItems, null, 2)};\n\n` +
    `export const registryItemsByName: Record<string, DocRegistryItem> = Object.fromEntries(\n` +
    `  registryItems.map((item) => [item.name, item]),\n` +
    `);\n`,
  'utf8',
);

/* ── 3. Prop tables, from the TypeScript types ─────────────────────────────── */

/**
 * Props are extracted rather than written, because a hand-written table for 38
 * components is 38 places for the documentation to disagree with the code , and
 * it disagrees silently, which is the worst way for documentation to be wrong.
 *
 * The filter is a DENYLIST of the packages a component forwards to, not an
 * allowlist of our own files. That is deliberate: `VariantProps<typeof
 * buttonVariants>` resolves through `class-variance-authority`, so an
 * "only props declared in registry/velobits" rule would drop `variant` and
 * `size` , the two props anyone actually came to read.
 */
const FORWARDED_FROM = [
  'node_modules/@types/react',
  'node_modules/radix-ui',
  'node_modules/@radix-ui',
  'node_modules/framer-motion',
  'node_modules/react-hook-form',
  'node_modules/cmdk',
  'node_modules/typescript/lib',
];

const parser = withCustomConfig(join(docsDir, 'tsconfig.json'), {
  savePropValueAsString: true,
  shouldExtractLiteralValuesFromEnum: true,
  shouldRemoveUndefinedFromOptional: true,
  skipChildrenPropWithoutDoc: false,
  propFilter: (prop: PropItem) => {
    const declarations = prop.declarations ?? [];
    if (!declarations.length) return true;
    // Normalised because these are Windows paths here and POSIX paths in CI.
    return !declarations.every((d) =>
      FORWARDED_FROM.some((needle) => d.fileName.replace(/\\/g, '/').includes(needle)),
    );
  },
});

/**
 * `cva`'s `defaultVariants`, read straight from the AST.
 *
 * react-docgen-typescript reports a default only when it can see a
 * `defaultProps` or a destructured parameter default. A cva variant has neither:
 * the fallback lives in the config object passed to `cva()`, several statements
 * above the component. So the most useful column in the table , what you get if
 * you pass nothing , would be empty for exactly the props that have interesting
 * defaults.
 */
function cvaDefaults(sourceFile: ts.SourceFile): Record<string, string> {
  const defaults: Record<string, string> = {};

  const visit = (node: ts.Node): void => {
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === 'cva' &&
      node.arguments.length > 1
    ) {
      const config = node.arguments[1];
      if (config && ts.isObjectLiteralExpression(config)) {
        for (const prop of config.properties) {
          if (
            ts.isPropertyAssignment(prop) &&
            prop.name.getText(sourceFile) === 'defaultVariants' &&
            ts.isObjectLiteralExpression(prop.initializer)
          ) {
            for (const entry of prop.initializer.properties) {
              if (!ts.isPropertyAssignment(entry)) continue;
              defaults[entry.name.getText(sourceFile).replace(/^['"]|['"]$/g, '')] =
                entry.initializer.getText(sourceFile).replace(/^'|'$/g, '"');
            }
          }
        }
      }
    }
    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return defaults;
}

/**
 * react-docgen-typescript reports a hand-written union (`surface?: 'glass' | 'panel'`)
 * as the literal string `"enum"`, with the members hiding in `type.value`. A
 * table column reading "enum" tells a reader nothing they did not already know,
 * so the members are put back. Unions it expands itself , the cva-derived ones ,
 * arrive already spelled out and pass through untouched.
 */
function typeName(type: PropItem['type']): string {
  if (type.name !== 'enum' || !Array.isArray(type.value)) return type.name;

  const members = (type.value as { value?: unknown }[])
    .map((member) => String(member.value ?? ''))
    .filter((value) => value !== '' && value !== 'undefined');

  return members.length ? members.join(' | ') : type.name;
}

/**
 * The two default-value sources disagree about quoting: a destructured parameter
 * default arrives as `glass`, while the cva `defaultVariants` pass produces
 * `"glass"`. Both describe a string, and a table showing one of each reads as if
 * the difference were meaningful.
 */
function normaliseDefault(value: string | null, type: string): string | null {
  if (value == null) return null;
  if (/^["'`]/.test(value)) return value.replace(/'/g, '"');
  // Only quote when the type says it is a string literal, so `0`, `false` and
  // `() => {}` are left alone.
  return type.includes(`"${value}"`) ? `"${value}"` : value;
}

interface DocProp {
  name: string;
  type: string;
  required: boolean;
  defaultValue: string | null;
  description: string;
}

interface DocPropGroup {
  displayName: string;
  props: DocProp[];
}

const componentProps: Record<string, DocPropGroup[]> = {};
const noProps: string[] = [];

for (const item of registry.items) {
  const file = item.files?.[0];
  if (!file) continue;

  const absolute = join(root, file.path);
  const source = readFileSync(absolute, 'utf8');
  const defaults = cvaDefaults(
    ts.createSourceFile(absolute, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX),
  );

  let parsed;
  try {
    parsed = parser.parse([absolute]);
  } catch (error) {
    // A component whose types defeat the parser is a missing table, not a failed
    // build , the rest of its page is still correct and still worth shipping.
    console.warn(`  props: ${item.name} could not be parsed (${(error as Error).message})`);
    noProps.push(item.name);
    continue;
  }

  const groups: DocPropGroup[] = parsed
    .map((component) => ({
      displayName: component.displayName,
      props: Object.values(component.props)
        .map((prop): DocProp => {
          const type = typeName(prop.type);
          const raw =
            prop.defaultValue?.value != null
              ? String(prop.defaultValue.value)
              : (defaults[prop.name] ?? null);
          return {
            name: prop.name,
            type,
            required: prop.required,
            defaultValue: normaliseDefault(raw, type),
            description: prop.description,
          };
        })
        // A prop the checker resolved to bare `undefined` is one the component
        // explicitly Omits from what it forwards. It is not part of the API, and
        // a row reading `undefined` in the Type column suggests it is.
        .filter((prop) => prop.type !== 'undefined')
        .sort((a, b) => {
          // Required first , they are the ones you cannot skip reading.
          if (a.required !== b.required) return a.required ? -1 : 1;
          return a.name.localeCompare(b.name);
        }),
    }))
    .filter((group) => group.props.length > 0);

  if (groups.length) componentProps[item.name] = groups;
  else noProps.push(item.name);
}

writeFileSync(
  join(outDir, 'props.ts'),
  BANNER +
    `export interface DocProp {\n` +
    `  name: string;\n` +
    `  type: string;\n` +
    `  required: boolean;\n` +
    `  defaultValue: string | null;\n` +
    `  description: string;\n` +
    `}\n\n` +
    `export interface DocPropGroup {\n` +
    `  displayName: string;\n` +
    `  props: DocProp[];\n` +
    `}\n\n` +
    `/** Keyed by registry item name. Absent means the extractor found nothing to show. */\n` +
    `export const componentProps: Record<string, DocPropGroup[]> = ${JSON.stringify(componentProps, null, 2)};\n`,
  'utf8',
);

/* ── 4. Per-component content, validated against what exists ───────────────── */

/**
 * `apps/docs/content/components.ts` is prose, so nothing can derive it , but both
 * halves of every entry point at something that CAN be checked. An example name
 * that does not exist renders an empty preview; a content entry for a component
 * that was removed renders nothing at all. Both are silent, so both fail here.
 */
const exampleNames = new Set(exampleFiles.map((f) => f.replace(/\.tsx$/, '')));
const contentProblems: string[] = [];

/**
 * Words, lowercased and stripped of punctuation, for the duplication check below.
 */
function words(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter(Boolean);
}

/**
 * Longest run of words `note` shares with `description`.
 *
 * ## Why the build cares
 *
 * A component page prints the registry description and then the notes, one after
 * the other. The registry descriptions are already paragraphs of rationale, so a
 * note that restates one reads as padding , the reader hits the same sentence
 * twice and learns to skim both. The first draft of `content.ts` did this on 30
 * notes across 25 pages, which is how this check came to exist.
 *
 * Notes are for what the description does NOT say: the measurement behind a
 * claim, the call site that motivated a prop, the failure mode. Sixteen words is
 * a deliberately loose threshold , it catches a copied sentence without
 * complaining about two paragraphs that necessarily share a component's name and
 * a few connectives.
 */
function longestSharedRun(note: string, description: string): number {
  const noteWords = words(note);
  const haystack = words(description).join(' ');
  let longest = 0;

  for (let start = 0; start < noteWords.length; start += 1) {
    let length = longest;
    // Only ever try to BEAT the current best, so this stays near-linear rather
    // than checking every window.
    while (
      start + length < noteWords.length &&
      haystack.includes(noteWords.slice(start, start + length + 1).join(' '))
    ) {
      length += 1;
      longest = length;
    }
  }

  return longest;
}

const MAX_SHARED_RUN = 16;

for (const [name, content] of Object.entries(COMPONENT_CONTENT)) {
  if (!registryNames.includes(name)) {
    contentProblems.push(`content for "${name}", which is not a registry item`);
  }
  for (const example of content.examples ?? []) {
    if (!exampleNames.has(example.name)) {
      contentProblems.push(
        `"${name}" lists example "${example.name}", which is not a file in apps/docs/registry/examples/`,
      );
    }
  }

  const description = registry.items.find((item) => item.name === name)?.description ?? '';
  (content.notes ?? []).forEach((note, index) => {
    const shared = longestSharedRun(note, description);
    if (shared > MAX_SHARED_RUN) {
      contentProblems.push(
        `"${name}" notes[${index}] repeats ${shared} consecutive words of the registry ` +
          `description, which is printed directly above it. Say what the description does not.`,
      );
    }
  });
}

if (contentProblems.length) {
  console.error(
    '\napps/docs/content/components.ts points at things that do not exist:\n  ' +
      contentProblems.join('\n  '),
  );
  process.exit(1);
}

interface EmittedContent {
  usage: { source: string; html: string } | null;
  examples: { name: string; title: string | null; description: string | null }[];
  notes: string[];
}

const emittedContent: Record<string, EmittedContent> = {};
for (const [name, content] of Object.entries(COMPONENT_CONTENT)) {
  emittedContent[name] = {
    usage: content.usage
      ? {
          source: content.usage,
          // The theme item's snippet is CSS; everything else is TSX. Getting this
          // wrong is not an error, just wrong colours, so it is worth the branch.
          html: await highlight(content.usage, name === 'velobits-theme' ? 'css' : 'tsx'),
        }
      : null,
    examples: (content.examples ?? []).map((example) => ({
      name: example.name,
      title: example.title ?? null,
      description: example.description ?? null,
    })),
    notes: [...(content.notes ?? [])],
  };
}

writeFileSync(
  join(outDir, 'content.ts'),
  BANNER +
    `export interface DocContentExample {\n` +
    `  name: string;\n` +
    `  title: string | null;\n` +
    `  description: string | null;\n` +
    `}\n\n` +
    `export interface DocContent {\n` +
    `  usage: { source: string; html: string } | null;\n` +
    `  examples: DocContentExample[];\n` +
    `  notes: string[];\n` +
    `}\n\n` +
    `/** Keyed by registry item name. Absent is normal , every field is optional. */\n` +
    `export const componentContent: Record<string, DocContent> = ${JSON.stringify(emittedContent, null, 2)};\n`,
  'utf8',
);

/* ── 5. The ⌘K index ───────────────────────────────────────────────────────── */

interface SearchEntry {
  title: string;
  href: string;
  group: string;
  description: string;
}

const searchIndex: SearchEntry[] = [
  ...emittedItems.map((item) => ({
    title: item.title,
    href: `/docs/components/${item.name}`,
    group: item.group,
    // One line in a palette row. The registry descriptions are paragraphs.
    description: item.description.split(/(?<=\.)\s/)[0] ?? '',
  })),
];

// Guide pages come from the same nav the sidebar renders, so the two cannot
// disagree about what exists.
for (const group of GUIDE_NAV) {
  for (const entry of group.items) {
    searchIndex.push({
      title: entry.title,
      href: entry.href,
      group: group.title,
      description: entry.description ?? '',
    });
  }
}

writeFileSync(
  join(docsDir, 'public/search-index.json'),
  JSON.stringify(searchIndex, null, 2) + '\n',
  'utf8',
);

/* ── 6. The agent skill ────────────────────────────────────────────────────── */

/**
 * `skills/velobits-ui/` is the source, and it leaves here two ways:
 *
 *   public/skills/velobits-ui/…   the files themselves, so the docs origin serves
 *                                 them for the `curl` install and for any agent
 *                                 that can fetch a URL
 *   public/r/skill.json           a `registry:file` item whose targets are
 *                                 `.claude/skills/…`, so
 *                                 `npx shadcn add <origin>/r/skill.json` installs
 *                                 it into a consumer's repo
 *
 * Deliberately NOT an entry in `registry/registry.ts`: it has no source under
 * `registry/velobits/`, and every item in that list gets a component page plus a
 * sidebar slot (section 0 above enforces exactly that). `/docs/skill` is its page.
 * `shadcn build` has already run by the time this does, and it only writes the
 * items it compiled, so one more file in that folder survives.
 *
 * ⚠️ `target` must keep the `~/` prefix. That is the CLI's spelling for "the
 * project root"; without it the path goes through alias resolution instead, and
 * `.claude/…` is not an alias.
 */
const SKILL_NAME = 'velobits-ui';
const skillDir = join(root, 'skills', SKILL_NAME);

const skillReferences = readdirSync(join(skillDir, 'references'))
  .filter((f) => f.endsWith('.md'))
  .sort()
  .map((f) => `references/${f}`);

const skillEntry = readFileSync(join(skillDir, 'SKILL.md'), 'utf8');
const linkedReferences = new Set(
  [...skillEntry.matchAll(/references\/[a-z0-9-]+\.md/g)].map((m) => m[0]),
);

/*
 * Same idea as section 0, for the same reason. A `SKILL.md` pointing at a
 * reference file that is not there sends a model off to invent the answer, which
 * is worse than shipping no skill , and a reference file nothing points at is
 * never read. Neither is visible by looking at the rendered docs, so it fails the
 * build by name instead.
 */
const skillProblems = [
  ...[...linkedReferences]
    .filter((f) => !skillReferences.includes(f))
    .map((f) => `SKILL.md links ${f}, which does not exist`),
  ...skillReferences
    .filter((f) => !linkedReferences.has(f))
    .map((f) => `${f} exists, but SKILL.md never points at it`),
];

if (skillProblems.length) {
  console.error(`\nskills/${SKILL_NAME} is inconsistent:\n  ` + skillProblems.join('\n  '));
  process.exit(1);
}

const skillFiles = ['SKILL.md', ...skillReferences];
const publicSkillDir = join(docsDir, 'public/skills', SKILL_NAME);

const skillItemFiles = skillFiles.map((relative) => {
  const source = readFileSync(join(skillDir, relative), 'utf8');
  const installed = `.claude/skills/${SKILL_NAME}/${relative}`;

  const copy = join(publicSkillDir, relative);
  mkdirSync(dirname(copy), { recursive: true });
  writeFileSync(copy, source, 'utf8');

  return { path: installed, content: source, type: 'registry:file', target: `~/${installed}` };
});

/** The frontmatter `description`, so the registry item cannot describe it differently. */
const skillDescription =
  /^---\r?\n[\s\S]*?^description:\s*(.+)$/m.exec(skillEntry)?.[1]?.trim() ?? '';

writeFileSync(
  join(docsDir, 'public/r/skill.json'),
  JSON.stringify(
    {
      $schema: 'https://ui.shadcn.com/schema/registry-item.json',
      name: 'skill',
      type: 'registry:file',
      title: 'VeloBits agent skill',
      description: skillDescription,
      files: skillItemFiles,
      docs: `Installed to .claude/skills/${SKILL_NAME}/. Point your agent at it, or ask it to read SKILL.md before touching UI.`,
    },
    null,
    2,
  ) + '\n',
  'utf8',
);

/* ── 7. Report ─────────────────────────────────────────────────────────────── */

console.log(`docs data → apps/docs/lib/generated/`);
console.log(`  examples.ts       ${exampleFiles.length} examples`);
console.log(`  registry-data.ts  ${emittedItems.length} items`);
console.log(`  content.ts        ${Object.keys(emittedContent).length} items with content`);
console.log(`  props.ts          ${Object.keys(componentProps).length} items with prop tables`);
console.log(`  search-index.json ${searchIndex.length} entries`);
console.log(`  skills/${SKILL_NAME}  ${skillFiles.length} files, plus r/skill.json`);

if (noProps.length) {
  /*
   * Printed rather than swallowed. An empty prop table renders as an absent
   * section, which looks identical to "this component has no props" , so without
   * this line a regression in the extractor is invisible until someone goes
   * looking for a prop they know exists.
   */
  console.log(`\n  no props extracted for ${noProps.length}: ${noProps.join(', ')}`);
}
